-- AlterTable
ALTER TABLE `posts` MODIFY `price` DOUBLE NULL DEFAULT 0,
    MODIFY `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updated_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `views` INTEGER NULL DEFAULT 0;
